### DISCUSSION TITLE
Jeg ønsker meg eksempler på gode og dårlige tabeller

### DISCUSSION THREAD

**Discussion by joms** [fremtind/jokul#2804] [Annet]
Å lage gode tabeller er overraskende vanskelig. Nedenfor er 3 eksempler på en tabell som inneholder akkurat de samme dataene, men har litt forskjellige regler for luft i tabellen.

### Default oppsett
![image](https://user-images.githubusercontent.com/537060/158559704-63c13337-5a3c-4b9b-8ec9-b4608e5c8c20.png)

### Unngå at tekst wrapper i noen kolonner

```css
.jkl-table-cell:not([data-th="Status"]) {
    white-space: no-wrap;
}
```

![image](https://user-images.githubusercontent.com/537060/158559915-5a424dcd-e5bc-4cbf-8e18-df397bbc3864.png)

### Lås bredden på én kolonne, og la resten justere seg

```css
.jkl-table-cell[data-th="Status"] {
    width: 30%;
}
```

![image](https://user-images.githubusercontent.com/537060/158560050-921ca625-b14d-4574-9daa-e55d6dbf9878.png)

## Problemet

Hver av disse løsningene drar med seg forskjellige utfordringer knyttet til skjermstørrelser og responsivitet. Noen blir trange, men sikrer at alle kolonner kan leses på en god måte. Andre knekker tekst, men sikrer luft osv.

Her skulle jeg ønske at vi hadde noen gode eksempler med kode som viser forskjellige metoder som kan fungere til å kontrollere kolonnebredder og sikre lesbarhet.
