### ISSUE TITLE
Feil: Fokusmarkering på controller-button i autosuggest

### ISSUE THREAD

**Issue by daa1** [fremtind/jokul#2686]
## Feilbeskrivelse

Det finnes ingen fokusmarkering på controller-button ved tabbing i komponenten.

## Steg for å gjenskape

1. Gå til [Jøkul Autosuggest](https://jokul.fremtind.no/komponenter/autosuggest)
2. Klikk på 'Vis ikoner'
3. Sett fokus på autosuggest feltet og bruk tab, og man vil se at det mangler en indikator på at ikon/controller-button er i fokus

## Forventet oppførsel

Forventer en form for fokusmarkering, om dette er bruk av box-shadow og border-radius som på text-input eller noe annet kan vurderes.

## Systeminformasjon

macOS 12.1, Chrome 97.0.4692.99

**Comment by wkillerud** [comment]
Hei @daa1, og takk for bugrapport! Det kommer en redesign av hvordan skjemafelter ser ut når de har valideringsfeil, forhåpentligvis i løpet av de neste par ukene. I forbindelse med det vil Autosuggest få fokusmarkering på knappene 😄 

- #2635 

![Skjermbilde av Autosuggest sitt ikon med en fokusramme rundt](https://user-images.githubusercontent.com/1223410/151814858-a50bed0d-c3b1-49fb-b6bd-aef2315af525.png)

Hvis det haster så kan du ta en titt på koden her for å hente ut de relevante tingene, og legge det til i eget prosjekt inntil videre:

https://github.com/fremtind/jokul/pull/2635/files?file-filters%5B%5D=.scss&show-deleted-files=true&show-viewed-files=true#diff-d752fd291796008b430f4b8c7f97c1b8894929e836ad873cfbb99e85b9a42ac2


```scss
@use "~@fremtind/jkl-core/jkl";

@import "~@fremtind/jkl-core/mixins/_all.scss";

@include light-mode-variables {
     --autosuggest-focus-color: #{jkl.$color-granitt};
 }

 @include dark-mode-variables {
     --autosuggest-focus-color: #{jkl.$color-snohvit};
 }

.jkl-autosuggest__controller-button:focus {
       @include keyboard-navigation {
           &::after {
               content: "";
               position: absolute;
               top: rem(8px);
               right: rem(8px);
               bottom: rem(8px);
               left: rem(8px);
               box-shadow: inset 0 0 0 rem(2px) var(--autosuggest-focus-color);
           }
       }
   }
```
