### ISSUE TITLE
Default focus-outline is turned off

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#386]
**Describe the bug**
In the global CSS, the default focus outline is disabled.

If you use a component or element that has a focused-state and isn't part of Jøkul, all focus indication is gone.

This is very likely to happen in Fremtind-applications and is very cumbersome to work with as you have to override the override if you want outline.

**Expected behavior**
To be able to use jkl-core and have default outline styling.

**Comment by piofinn** [comment]
This should be looked at when working on #385. To keep things simple when we create new components, we can perhaps consider a small mixin to remove outlines (general and browser-specific) for the component:

```scss
@mixin remove-outline() {
    outline: none;
    & * {
        outline: none;
    }
    & *:-moz-focusring {
        color: transparent;
        text-shadow: 0 0 0 #000;
    }
    // etc.
}
```
