### ISSUE TITLE
Feil bakgrunnsfarge på valgt tekst

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#4837]
I chromium-nettlesere på Windows mangler fargen på tekstutheving i tekstfeltene gjennomsiktighet, slik at man ikke kan se teksten som er valgt.

![Image](https://github.com/user-attachments/assets/d0c26550-c174-49db-a18f-b581f4cc128b)

Testet i Edge og Chrome 136

**Comment by piofinn** [comment]
Dette kommer sannsynligvis fra endringen som ble innført da vi gikk over til semantiske variabler i `text-input`:

```scss
// Color of text selection
&::selection {
    background-color: color(from currentColor sRGB r g b / 0.25);
}
```

`color()`-funksjonen skal ha god støtte i Chromium, så denne er litt mystisk. Vi skal forsøke å få feilsøkt sammen med teamet som meldte inn.
